# Generated by Django 3.2.6 on 2021-09-18 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmessage_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-date_sent']},
        ),
    ]
