# Generated by Django 3.2.6 on 2021-08-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='speciality',
            field=models.CharField(default='', max_length=15),
        ),
    ]
